import { StyleSheet, StatusBar } from "react-native";

export const styles = StyleSheet.create({
    root:{
        marginTop: StatusBar.currentHeight || 0,
        flex: 1
    },
    container:{
        width: '80%',
        marginHorizontal: 'auto'
    },
    buttonDefault:{
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#395DD3',
        width:360,
        height:60,
    },
    buttonDefaultMin:{
        width:150,
        height:50,
        borderBottomColor:'#54A7F4',
        borderBottomWidth:5
    },
    buttonDark:{
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#20202A',
        width:360,
        height:60
    },
    buttonLoginGoogle:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        borderColor:'#20202A',
        borderWidth:3,
        width:350,
        height:60,
    },
    inputUser:{
        paddingLeft: 12,
        flexDirection:'row',
        borderColor:'#7B8499',
        borderWidth:2,
        alignItems:'center',
        width:350,
        gap: 4,
        height:60,
    },
    containerAccessOption:{
        position:'absolute',
        bottom:0,
        height:'55%',
        backgroundColor:'#eef2f9',
        borderTopLeftRadius:40,
        borderTopRightRadius:40,
        gap:50
    },
    containerButtons:{
        height:'40%'
    },
    flexDirectionRow:{
        flexDirection:'row'
    },
    alignItemsCenter:{
        alignItems:'center'
    },
    justifyContentCenter:{
        justifyContent:'center'
    },
    Roboto_Flex:{
    },
    borderRadius1:{
        borderRadius:5
    },
    borderRadius2:{
        borderRadius:10
    },
    borderRadius3:{
        borderRadius:15
    },
    fontSize1:{
        fontSize:12
    },
    fontSize2:{
        fontSize:14
    },
    fontSize3:{
        fontSize:16
    },
    fontSize4:{
        fontSize:20
    },
    fontSize5:{
        fontSize:24
    },
    fontSize6:{
        fontSize:28
    },
    fontSize7:{
        fontSize:32
    },
    fontSize8:{
        fontSize:40
    },
    fontSize9:{
        fontSize:68
    },
    fontWeightMedium:{
        fontWeight:"500"
    },
    fontWeightBold:{
        fontWeight:'bold'
    },
    gap1:{
        gap:5
    },
    gap2:{
        gap:10
    },
    gap3:{
        gap:15
    },
    padding1:{
        padding:5
    },
    padding2:{
        padding:10
    },
    padding3:{
        padding:15
    },
    margin1:{
        margin:5
    },
    margin2:{
        margin:10
    },
    margin3:{
        margin:16
    },
    margin4:{
        margin:20
    },
    margin5:{
        margin:25
    },
    marginLeft1:{
        marginLeft:5
    },
    marginLeft2:{
        marginLeft:10
    },
    marginLeft3:{
        marginLeft:16
    },
    marginLeft4:{
        marginLeft:20
    },
    marginLeft5:{
        marginLeft:25
    }
    ,
    marginRight1:{
        marginRight:5
    },
    marginRight2:{
        marginRight:10
    },
    marginRight3:{
        marginRight:16
    },
    marginRight4:{
        marginRight:20
    },
    marginRight5:{
        marginRight:25
    }
})