import { StyleSheet, StatusBar } from "react-native";

export const styles = StyleSheet.create({
    root:{
        flex:1,
        marginHorizontal:'auto',
        width:'100%',
    },
    centralizeItems:{
        alignItems:'center',
        justifyContent:'center',
    },
    buttonDefault:{
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#395DD3',
        width:360,
        height:60,
    },
    buttonDark:{
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#20202A',
        width:360,
        height:60
    },
    buttonLoginGoogle:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        borderColor:'#20202A',
        borderWidth:3,
        width:350,
        height:60,
    },
    inputUser:{
        flexDirection:'row',
        borderColor:'#20202A',
        borderWidth:3,
        alignItems:'center',
        width:350,
        height:60,
    },
    WelcomeSquare:{
        position:'absolute',
        alignItems:'center',
        borderTopRightRadius: 40,
        borderTopLeftRadius:40,
        bottom:0,
        backgroundColor:'white',
        width:'100%',
        height:'50%',
    },
    TextHeader:{
        color:'#20202A',
        fontSize:32,
        fontWeight:'bold'
    },
    borderRadius1:{
        borderRadius:5
    },
    borderRadius2:{
        borderRadius:10
    },
    borderRadius3:{
        borderRadius:15
    },
    fontSize1:{
        fontSize:15
    },
    fontSize2:{
        fontSize:20
    },
    fontSize3:{
        fontSize:25
    },
    gap1:{
        gap:5
    },
    gap2:{
        gap:10
    },
    gap3:{
        gap:15
    },
    padding1:{
        padding:5
    },
    padding2:{
        padding:10
    },
    padding3:{
        padding:15
    },
})